<?php get_header();
$audiences = auvenda_field('audience_cards', array()); $steps = auvenda_field('journey_steps', array()); $features = auvenda_field('providers_features', array());
if (!$audiences) $audiences = array(array('number'=>'01','title'=>'For Seafarers','text'=>'Find professional training and plan your certification path.'),array('number'=>'02','title'=>'For Training Providers','text'=>'Reach new markets while keeping control of your learning experience.'),array('number'=>'03','title'=>'For Shipping Companies','text'=>'Coordinate crew development and see training status clearly.'));
if (!$steps) $steps = array(array('number'=>'01','title'=>'Find','text'=>'Discover suitable training'),array('number'=>'02','title'=>'Enroll','text'=>'Choose a provider and format'),array('number'=>'03','title'=>'Learn','text'=>'Build professional knowledge'),array('number'=>'04','title'=>'Assess','text'=>'Confirm competency'),array('number'=>'05','title'=>'Certify','text'=>'Keep results available'));
if (!$features) $features = array(array('feature'=>'Publish courses'),array('feature'=>'Manage students'),array('feature'=>'Deliver learning materials'),array('feature'=>'Track progress'),array('feature'=>'Conduct assessments'),array('feature'=>'Issue certificates'));
?><main>
<?php if (!auvenda_field('disable_hero_section', false)): ?><section class="hero"><div class="container"><p class="eyebrow"><?php echo esc_html(auvenda_field('hero_eyebrow','EUROPE · MARITIME TRAINING PLATFORM')); ?></p><h1><?php echo wp_kses_post(auvenda_field('hero_title','Maritime Training.<br><em>Connected.</em>')); ?></h1><p class="lead"><?php echo esc_html(auvenda_field('hero_text','One platform connecting seafarers, maritime training providers and shipping companies across international markets.')); ?></p><?php echo auvenda_link('hero_cta_link',auvenda_field('hero_cta_label','Explore training'),get_post_type_archive_link('course')); ?> <?php echo auvenda_link('hero_second_cta_link',auvenda_field('hero_second_cta_label','Become a Training Partner'),'#providers'); ?></div></section><?php endif; ?>
<?php if (!auvenda_field('disable_audiences_section', false)): ?><section class="section audiences"><div class="container"><p class="eyebrow"><?php echo esc_html(auvenda_field('audiences_eyebrow','WHO THE PLATFORM SERVES')); ?></p><h2><?php echo wp_kses_post(auvenda_field('audiences_title','One journey.<br>Three perspectives.')); ?></h2><p><?php echo esc_html(auvenda_field('audiences_text','Find the path that reflects your role in the maritime ecosystem.')); ?></p><div class="cards"><?php foreach($audiences as $card): ?><article><small><?php echo esc_html($card['number'] ?? ''); ?></small><h3><?php echo esc_html($card['title'] ?? ''); ?></h3><p><?php echo esc_html($card['text'] ?? ''); ?></p><?php if(!empty($card['cta']['url'])): ?><a href="<?php echo esc_url($card['cta']['url']); ?>"><?php echo esc_html($card['cta']['title']); ?> →</a><?php endif; ?></article><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if (!auvenda_field('disable_journey_section', false)): ?><section class="section journey"><div class="container"><p class="eyebrow"><?php echo esc_html(auvenda_field('journey_eyebrow','A CLEAR TRAINING JOURNEY')); ?></p><h2><?php echo wp_kses_post(auvenda_field('journey_title','From course search<br>to certification.')); ?></h2><div class="steps"><?php foreach($steps as $step): ?><article><small><?php echo esc_html($step['number'] ?? ''); ?></small><h3><?php echo esc_html($step['title'] ?? ''); ?></h3><p><?php echo esc_html($step['text'] ?? ''); ?></p></article><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if (!auvenda_field('disable_courses_section', false)): ?><section class="section courses-preview"><div class="container"><p class="eyebrow"><?php echo esc_html(auvenda_field('courses_eyebrow','PLANNED COURSE CATALOGUE')); ?></p><h2><?php echo esc_html(auvenda_field('courses_title','Explore training directions.')); ?></h2><?php echo auvenda_link('courses_cta','View all training',get_post_type_archive_link('course')); ?><div class="course-directions"><?php foreach(get_terms(array('taxonomy'=>'course_direction','hide_empty'=>false)) as $term): ?><a href="<?php echo esc_url(get_term_link($term)); ?>"><span><?php echo esc_html($term->name); ?></span><b>→</b></a><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if (!auvenda_field('disable_providers_section', false)): ?><section class="section providers" id="providers"><div class="container split"><div><p class="eyebrow"><?php echo esc_html(auvenda_field('providers_eyebrow','FOR TRAINING PROVIDERS')); ?></p><h2><?php echo wp_kses_post(auvenda_field('providers_title','Bring your maritime<br>training online.')); ?></h2><p><?php echo esc_html(auvenda_field('providers_text','Connect your centre to a wider market while keeping control of courses, learners and training standards.')); ?></p><?php echo auvenda_link('providers_cta','Become a Training Partner','#contact'); ?></div><div class="feature-list"><?php foreach($features as $feature): ?><span>› <?php echo esc_html($feature['feature'] ?? ''); ?></span><?php endforeach; ?></div></div></section><?php endif; ?>
<?php if (!auvenda_field('disable_companies_section', false)): ?><section class="section companies" id="companies"><div class="container split"><div class="company-card"><?php echo esc_html(auvenda_field('companies_card_title','CREW MANAGERS')); ?></div><div><p class="eyebrow"><?php echo esc_html(auvenda_field('companies_eyebrow','FOR SHIPPING COMPANIES')); ?></p><h2><?php echo wp_kses_post(auvenda_field('companies_title','Manage crew training<br>in one place.')); ?></h2><p><?php echo esc_html(auvenda_field('companies_text','Source suitable courses, coordinate enrolment and retain a clear view of the crew’s training status.')); ?></p><?php echo auvenda_link('companies_cta','Discuss corporate training','#contact'); ?></div></div></section><?php endif; ?>
<?php if (!auvenda_field('disable_form_section', false)): ?><section class="section contact-section" id="contact"><div class="container split"><div><p class="eyebrow"><?php echo esc_html(auvenda_field('form_eyebrow','START A CONVERSATION')); ?></p><h2><?php echo wp_kses_post(auvenda_field('form_title','How can we<br>help?')); ?></h2><p><?php echo esc_html(auvenda_field('form_text','Choose the path that best describes you. We will collect only the information needed for the next step.')); ?></p></div><div class="form-wrap"><?php if (auvenda_field('form_source','cf7') === 'embed') { echo wp_kses_post(auvenda_field('form_embed')); } elseif ($form = auvenda_field('form_cf7')) { echo do_shortcode('[contact-form-7 id="' . absint(is_object($form) ? $form->ID : $form) . '"]'); } ?></div></div></section><?php endif; ?>
</main><?php get_footer(); ?>
